stages:
  - build
  - deploy

run-build:
  stage: build
  image: registry.gitlab.com/faucetsdn/faucet/dbuilder
  script:
    - apt-get update && apt-get upgrade -y
    - cd /builds/faucetsdn/python3-ryu
    - apt-get upgrade -y && mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='maintainers@faucet.nz' && export DEBFULLNAME='Faucet Maintainers'
    - fakeroot debian/rules binary
    - mkdir built-packages || true
    - mv ../*.deb built-packages/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

deploy-package:
  stage: deploy
  image: registry.gitlab.com/faucetsdn/faucet/dbuilder
  script:
    - cd /builds/faucetsdn/python3-ryu/built-packages/
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > ~/.packagecloud
    - package_cloud push faucetsdn/faucet/debian/jessie *.deb || true
    - package_cloud push faucetsdn/faucet/debian/stretch *.deb || true
    - package_cloud push faucetsdn/faucet/debian/buster *.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/jessie *.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/stretch *.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/buster *.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/xenial *.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/yakkety *.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/zesty *.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/artful *.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/bionic *.deb || true
